### ISSUE TITLE
Ideas needed!

### ISSUE THREAD

**Issue by maradotwebp** [froehlichA/apidown#1]
Leave your idea here, or submit a pull request to APP.md.

**Comment by sachincool** [comment]
I am Confused , Do you need Ideas regarding new api  ? what more we can add to it ?

**Comment by maradotwebp** [comment]
@sachincool Please check out App.md. There is a basic idea for how the app should work. You can add new ideas what the app can/should do.

**Comment by radding** [comment]
I was thinking about defining the API when you create the API. For example something like: ```api('www.sample-api.com')
    .key('MY_API_KEY')
    .get("users", "/users")```

Then later you could do things like 
```api.users().then(() => {. . . });```

I would also like to use promises.

**Comment by maradotwebp** [comment]
@radding nice, that's a good idea!

I've already thought about preloading URLs, so when defining
```api('www.sample-api.com').preload(\/users\/[0-1000]\) ```
the api preloads all urls matching the RegExp and stores them in the cache.

Please make a pull request regarding your ideas, and put them into App.md!

**Comment by radding** [comment]
@froehlichA Requested PR is up: #9. Thanks!
