### ISSUE TITLE
Add plaintext authentication

### ISSUE THREAD

**Issue by maradotwebp** [froehlichA/apidown#12]
Support for simple API key or password auth.

**Comment by FrancescoSaverioZuppichini** [comment]
Hello :) I like this project. I will try to do it. Should I add some parameter in the `fetch` function, like `key`?

**Comment by maradotwebp** [comment]
@FrancescoSaverioZuppichini Thanks for your interest! Yes, that would be a good idea. The fetch function currently accepts an 'option' object. Place your ```key``` in there.

Make sure to also write tests, and to reference this issue in your pull request.

**Comment by FrancescoSaverioZuppichini** [comment]
I look at the code and it may be smarted to pass an initial configuration so the client does not have to pass the key at each `fetch` call. What do you think? 

For the tests, I cannot use `runTestsWithApi` since I need to pass they `key` to each `fetch` call. So maybe we should think about passing a `defaultOptions` directly as a `Api`'s parameter

**Comment by maradotwebp** [comment]
@FrancescoSaverioZuppichini Sure you can. the ```runTestsWithApi``` function calls the ```dynamicFetch``` function, which accepts an ```option``` parameter and four callbacks for the four differenct cases. Just add your ```describe``` test to the ```runTestsWithApi```.

Regarding the initial configuration, this is something that will be done by me today.

**Comment by FrancescoSaverioZuppichini** [comment]
yes but I cannot pass `option` directly to `runTestWithApi` 

By the way, really nice work :)

**Comment by froehlichA** [comment]
@FrancescoSaverioZuppichini Look above

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect :) I will way for your updates

Also, usually API's key are passed using just a query parameter `key=API_KEY` in the url, but something they are also stored in the headers so I think that `request` should be like this:

https://github.com/request/request#custom-http-headers

instead of passing just the `url` as first parameter

**Comment by maradotwebp** [comment]
@FrancescoSaverioZuppichini I have included an ```authentication``` option in the ```defaultOptions``` object and a function, so you can now write:
```javascript
var api = require('apidown');
var testapi = api('www.google.com')
testapi.password('PW_KEY');
```
You can rewrite the ```password``` function and name to your liking.

I added a todo comment on the line [here](https://github.com/froehlichA/apidown/blob/3ff10b7d6c003b119ebf7520f7eb32211211250e/lib/index.js#L45) to indicate that password checking isn't implemented yet, so you just have to implement auth checking in ```onlineFirst``` and ```offlineFirst``` and write the unit tests.

**Comment by FrancescoSaverioZuppichini** [comment]
Nice :) I am going to implement just the normal query-url API key auth if that is okay.

**Comment by FrancescoSaverioZuppichini** [comment]
Hey, I see that you have changed the core code again. How can I pull my changes if all the core is now different?

**Comment by maradotwebp** [comment]
@FrancescoSaverioZuppichini It's the second day of the repo and the core is currently undergoing heavy rewriting. I'm sorry for this, but it's my first "real" open-source project and I'm trying to start off quickly. I'
ll try to be more consistent.

**Comment by FrancescoSaverioZuppichini** [comment]
No worries man :) This is my fist PL in a open source project so we are in the same boat
