### ISSUE TITLE
Promisify the api

### ISSUE THREAD

**Issue by maradotwebp** [froehlichA/apidown#13]
apidown currently relies on callbacks, but requests have been made to include and use promises.

**Comment by ypahalajani** [comment]
@froehlichA: I've started working on it. So, basically, the fetch method is to return a Promise, right?

**Comment by maradotwebp** [comment]
@ypahalajani: Yeah, that's basically it. @radding also referenced this in #1, but I don't know if he already started working on it.

**Comment by radding** [comment]
@froehlichA @ypahalajani If you look at PR #11, I have made the new defineEndpoint method and by extension get/put/post/delete/patch/resource methods return a promise. But I have left the fetch method the same.
