### ISSUE TITLE
If data has been preloaded or downloaded before, load the already downloaded data.

### ISSUE THREAD

**Issue by maradotwebp** [froehlichA/apidown#4]
Should download data from this url on first request, save url and data somewhere, and check on following requests if URL has already been requested.
[Link to code here.](https://github.com/froehlichA/apidown/blob/d947e910ff9a7ced6f9b873b36fb8292e0170ae4/lib/index.js#L33)

**Comment by Aidurber** [comment]
I'm happy to have a stab at this.

**Comment by ebukahills** [comment]
Will this package be used primarily from Node or the browser? so i know what caching mechanism to use

**Comment by maradotwebp** [comment]
@flyg101 primarily node.

**Comment by maradotwebp** [comment]
With data caching now implemented, we can close this.
